# Generated by Django 5.2.16 on 2026-08-04 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'maps',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'modes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'players',
                'ordering': ('name', 'player_id'),
            },
        ),
        migrations.CreateModel(
            name='CompetitionStage',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('season', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'competition_stages',
                'ordering': ('season', 'start_date'),
                'constraints': [models.UniqueConstraint(fields=('name', 'season'), name='unique_stage_per_season'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date')],
            },
        ),
        migrations.CreateModel(
            name='StageMapPoolEntry',
            fields=[
                ('pool_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_entries', to='src.gamemap')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_entries', to='src.gamemode')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_pool', to='src.competitionstage')),
            ],
            options={
                'db_table': 'stage_map_pool',
                'ordering': ('stage', 'mode__name', 'game_map__name'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('LAN', 'LAN'), ('ONLINE', 'Online')], max_length=10)),
                ('opponent', models.CharField(max_length=150)),
                ('event_date', models.DateTimeField(db_index=True)),
                ('pool_entry', models.ForeignKey(db_column='pool_entry_id', on_delete=django.db.models.deletion.PROTECT, related_name='games', to='src.stagemappoolentry')),
            ],
            options={
                'db_table': 'games',
                'ordering': ('-event_date', '-game_id'),
            },
        ),
        migrations.CreateModel(
            name='BettingLine',
            fields=[
                ('pk', models.CompositePrimaryKey('player_id', 'game_id', 'market', blank=True, editable=False, primary_key=True, serialize=False)),
                ('market', models.CharField(choices=[('KILLS', 'Kills'), ('KDR', 'Kill/death ratio')], max_length=10)),
                ('line', models.DecimalField(decimal_places=3, max_digits=8)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='betting_lines', to='src.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='betting_lines', to='src.player')),
            ],
            options={
                'db_table': 'betting_lines',
                'ordering': ('game_id', 'player_id', 'market'),
                'constraints': [models.CheckConstraint(condition=models.Q(('line__gte', 0)), name='betting_lines_line_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('pk', models.CompositePrimaryKey('player_id', 'game_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('kills', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=150)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='src.game')),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='src.player')),
            ],
            options={
                'db_table': 'player_game_stats',
                'ordering': ('game_id', 'player_id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('kills__gte', 0)), name='player_game_stats_kills_nonnegative'), models.CheckConstraint(condition=models.Q(('deaths__gte', 0)), name='player_game_stats_deaths_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='stagemappoolentry',
            constraint=models.UniqueConstraint(fields=('stage', 'game_map', 'mode'), name='stage_map_mode_unique_combination'),
        ),
    ]
