# Generated by Django 5.2.16 on 2026-08-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_bettingline_map_stat_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
