# Generated by Django 5.2.16 on 2026-08-05 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_game_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('alias_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('UNDERDOG', 'Underdog')], max_length=30)),
                ('external_player_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_aliases', to='src.player')),
            ],
            options={
                'db_table': 'player_aliases',
                'ordering': ('provider', 'display_name'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_player_id'), name='unique_provider_player')],
            },
        ),
        migrations.CreateModel(
            name='UnderdogMarket',
            fields=[
                ('underdog_market_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('stable_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('external_player_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_match_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=150)),
                ('opponent_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('display_stat', models.CharField(max_length=100)),
                ('series_game_number', models.PositiveSmallIntegerField()),
                ('stat_type', models.CharField(choices=[('KILLS', 'Kills'), ('DEATHS', 'Deaths')], max_length=20)),
                ('line', models.DecimalField(decimal_places=3, max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('UNMATCHED_PLAYER', 'Unmatched player'), ('UNMATCHED_GAME', 'Unmatched game'), ('AMBIGUOUS', 'Ambiguous'), ('UNSUPPORTED', 'Unsupported')], default='PENDING', max_length=30)),
                ('resolution_note', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='underdog_markets', to='src.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='underdog_markets', to='src.player')),
            ],
            options={
                'db_table': 'underdog_markets',
                'ordering': ('scheduled_at', 'player_name', 'series_game_number'),
                'constraints': [models.CheckConstraint(condition=models.Q(('line__gte', 0)), name='underdog_markets_line_nonnegative'), models.CheckConstraint(condition=models.Q(('series_game_number__gte', 1)), name='underdog_markets_game_number_positive')],
            },
        ),
    ]
