# Generated by Django 5.2.16 on 2026-08-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_underdogmarket_aggregate_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='source',
            field=models.CharField(choices=[('LAN', 'LAN'), ('ONLINE', 'Online'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
