# Generated by Django 5.2.16 on 2026-08-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_underdogmarket_aggregate_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalRoster',
            fields=[
                ('roster_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('season', models.PositiveSmallIntegerField()),
                ('team_name', models.CharField(max_length=150)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_roster_entries', to='src.player')),
            ],
            options={
                'db_table': 'professional_rosters',
                'ordering': ('season', 'team_name', 'display_order', 'player__name'),
                'constraints': [models.UniqueConstraint(fields=('season', 'team_name', 'player'), name='unique_professional_roster_entry'), models.UniqueConstraint(fields=('season', 'player'), name='unique_professional_roster_player')],
            },
        ),
    ]
