# Generated by Django 5.2.16 on 2026-08-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_game_source'),
        ('src', '0009_professionalroster'),
    ]

    operations = [
    ]
